### ISSUE TITLE
关于注意力模块的细节

### ISSUE THREAD

**Issue by guoyage** [joshyZhou/AST#10]
感谢作者如此精彩的工作，我有个疑问，为社么不在attn = attn0*w1+attn1*w2后再执行attn = self.softmax(attn)代码，此代码能够将注意力分数约束在[0, 1]之间。否则的话，注意力分数在[0, +无穷]的区间内，这并不符合注意力机制的原则。请您解释一下。谢谢

**Comment by joshyZhou** [comment]
你好，
softmax()函数是dense attention的成因，也是noisy interaction的来源。考虑到在attn = attn0w1+attn1w2后再执行attn = self.softmax(attn)，可能会分配给无关交互过高的注意力权重，我们没有进行该操作。具体的实验我们还没有做尝试，如果感兴趣可以基于我们的代码进行简单验证分析。
