### ISSUE TITLE
split step

### ISSUE THREAD

**Issue by Easesgr** [joshyZhou/AST#11]
![IMG_0026](https://github.com/user-attachments/assets/92dcb163-d7ea-4c02-b667-bfea87f35f96)
According to your code, the split of the image should be in the previous step?

**Comment by joshyZhou** [comment]
Thank you for your interest in our work. Indeed, Lines345-350 show the partial convolution operation, which also splits the features along the channel dimension. The `spilt' operation in the figure of the manuscript corresponds to Line 357.
