### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by 5chen** [joshyZhou/AST#4]
Hello! When will you release your full paper?

**Comment by joshyZhou** [comment]
Thank you for your interest in our work. We are pleased to inform you that our paper has been published online: [cvpr24_ast](https://openaccess.thecvf.com/content/CVPR2024/html/Zhou_Adapt_or_Perish_Adaptive_Sparse_Transformer_with_Attentive_Feature_Refinement_CVPR_2024_paper.html)

**Comment by joshyZhou** [comment]
Thanks for your interest in our work. We are pleased to inform you that our paper has been published online: [cvpr24_ast](https://openaccess.thecvf.com/content/CVPR2024/html/Zhou_Adapt_or_Perish_Adaptive_Sparse_Transformer_with_Attentive_Feature_Refinement_CVPR_2024_paper.html)
