### ISSUE TITLE
关于使用ASSA块和FRFN块的参数设置问题

### ISSUE THREAD

**Issue by LLLLLLLiu1211** [joshyZhou/AST#5]
我在我的模型中使用了ASSA块和FRFN块来代替attention以后，效果并不是特别理想，请问您在参数设置上有什么建议吗？

**Comment by joshyZhou** [comment]
你好，为了公平比较，我们的参数设置与Uformer(CVPR'22)一致，可以参考我们的原论文以及代码实现[model_utils.py](https://github.com/joshyZhou/AST/blob/main/utils/model_utils.py)获取更多细节，希望可以帮助到你。

**Comment by Patrickallll** [comment]
小白虚心请教作者大大，我在复现的过程中发现train_derain.py中
import options和
opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args()
这两个语句报错，请问options是自定义的包吗？
报错内容如下：Traceback (most recent call last):
  File "./train/train_derain.py", line 13, in <module>
    opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args()
  File "/root/anaconda3/envs/learn/lib/python3.7/site-packages/options/chainstuf.py", line 27, in __getattr__
    raise KeyError(key)
KeyError: 'init'

**Comment by renjianyanhuo** [comment]
> 我在我的模型中使用了ASSA块和FRFN块来代替attention以后，效果并不是特别理想，请问您在参数设置上有什么建议吗？
你好，是否方便加个微信交流一下，C1907401030

**Comment by guoyage** [comment]
> > 我在我的模型中使用了ASSA块和FRFN块来代替attention以后，效果并不是特别理想，请问您在参数设置上有什么建议吗？
> > 你好，是否方便加个微信交流一下，C1907401030

同样的使用ASSA模块替换了模型中的attention模块，模型性能反而降了很多。
