### ISSUE TITLE
小白请教关于train_derain.py中参数初始化报错

### ISSUE THREAD

**Issue by Patrickallll** [joshyZhou/AST#7]
小白虚心请教作者大大，我在复现的过程中发现train_derain.py中
import options和
opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args()
这两个语句报错，请问options是自定义的包吗？
报错内容如下：Traceback (most recent call last):
File "./train/train_derain.py", line 13, in
opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args()
File "/root/anaconda3/envs/learn/lib/python3.7/site-packages/options/chainstuf.py", line 27, in getattr
raise KeyError(key)
KeyError: 'init'

**Comment by Calvin11311** [comment]
> 小白虚心请教作者大大，我在复现的过程中发现train_derain.py中 import options和 opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args() 这两个语句报错，请问options是自定义的包吗？ 报错内容如下：Traceback (most recent call last): File "./train/train_derain.py", line 13, in opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args() File "/root/anaconda3/envs/learn/lib/python3.7/site-packages/options/chainstuf.py", line 27, in getattr raise KeyError(key) KeyError: 'init'

感谢反馈，已补充options.py文件

**Comment by renjianyanhuo** [comment]
> 小白虚心请教作者大大，我在复现的过程中发现train_derain.py中 import options和 opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args() 这两个语句报错，请问options是自定义的包吗？ 报错内容如下：Traceback (most recent call last): File "./train/train_derain.py", line 13, in opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args() File "/root/anaconda3/envs/learn/lib/python3.7/site-packages/options/chainstuf.py", line 27, in getattr raise KeyError(key) KeyError: 'init'

你好，请问你成功复现了吗，效果怎么样

**Comment by 72Wenhao** [comment]
> > 小白虚心请教作者大大，我在复现的过程中发现train_derain.py中 import options和 opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args() 这两个语句报错，请问options是自定义的包吗？ 报错内容如下：Traceback (most recent call last): File "./train/train_derain.py", line 13, in opt = options.Options().init(argparse.ArgumentParser(description='Image derain')).parse_args() File "/root/anaconda3/envs/learn/lib/python3.7/site-packages/options/chainstuf.py", line 27, in getattr raise KeyError(key) KeyError: 'init'
> 
> 你好，请问你成功复现了吗，效果怎么样

效果没有论文上写的那么好，去雨滴PSNR大概是29.多
