### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by hhhhhhalf** [joshyZhou/AST#9]
Hello, the experimental section of this paper mentions the model variant of 'AST-B+', but there is no model parameter setting for this in the model_utils.comy section of the code. May I ask how you designed the model parameters for 'AST-B+'?

**Comment by joshyZhou** [comment]
Hi,
The '+' symbol indicates the use of the geometric self-ensemble strategy. In fact, the model parameter settings for this case, as defined in model_utils.py, are identical to those used for 'AST-B'. I hope this response clarifies your concerns.
